# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Mehrdad Dastouri # the website title
name: Mehrdad Dastouri # your name
description: >- # A short bio about you. This will be displayed on the home page.
  A master's student in Artificial Intelligence at the University of Isfahan. 
  Passionate about machine learning, deep learning, and their applications 
  in real-world problems.

# Be sure to use the correct URL, otherwise paths to assets may not work correctly.
# In development, you can fill it with http://127.0.0.1:4000
# If you are deploying on GitHub Pages, the url should be http://<your-username>.github.io
url: "https://MehrdadDastouri.github.io" # the base hostname & protocol for your site
repository: "MehrdadDastouri/MehrdadDastouri.github.io" # the GitHub repository for your site
github_username: "MehrdadDastouri"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# You can add additional Jekyll plugins here. For more information, see https://jekyllrb.com/docs/plugins/
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-toc
  - jekyll-paginate
  - jemoji

# The following settings are for the default theme.
# It is recommended to modify these settings in a custom theme.
# For more information, see the documentation.
theme_settings:
  # The name of the theme.
  # The default theme is "al-folio".
  # You can find other themes at https://github.com/topics/al-folio-theme.
  # theme: al-folio

  # The name of the skin.
  # The default skin is "default".
  # You can find other skins at https://github.com/alshedivat/al-folio/tree/master/assets/css/jekyll-theme-conference.
  # skin: default

  # The title of the page.
  # The default title is the site title.
  # title: My awesome website

  # The description of the page.
  # The default description is the site description.
  # description: A short description of my awesome website.

  # The author of the page.
  # The default author is the site name.
  # author: John Doe

  # The favicon of the page.
  # The default favicon is /assets/img/favicon.ico.
  # favicon: /assets/img/favicon.ico

  # The logo of the page.
  # The default logo is /assets/img/logo.png.
  # logo: /assets/img/logo.png

  # The search bar.
  # The default is false.
  # search: false

  # The table of contents.
  # The default is false.
  # toc: false

  # The back to top button.
  # The default is false.
  # back_to_top: false

  # The number of posts to show on the home page.
  # The default is 5.
  # paginate: 5

  # The path to the pagination pages.
  # The default is /blog/page:num/.
  # paginate_path: /blog/page:num/

  # The social media links.
  # The default is an empty array.
  social:
    # behance: your_username
    # dribbble: your_username
    # facebook: your_username
    # flickr: your_username
    github: MehrdadDastouri
    # gitlab: your_username
    # google-scholar: your_username
    # instagram: your_username
    linkedin: mehrdad-dastouri
    # medium: your_username
    # pinterest: your_username
    # stack-overflow: your_username
    # telegram: your_username
    # twitter: your_username
    # vimeo: your_username
    # youtube: your_username

  # Google Analytics
  google_analytics: # your Google Analytics tracking ID

  # Google Search Console
  google_site_verification: "ln1BsUnngagfl1tX6PkrJN6u5neyG6VA1ZYuaCVFn7Y"

  # Bing Webmaster Tools
  bing_site_verification: # your Bing Webmaster Tools verification code

# -----------------------------------------------------------------------------
# Blog settings
# -----------------------------------------------------------------------------

# The title of the blog.
# The default is "blog".
blog_name: blog

# The description of the blog.
# The default is "a simple blog".
blog_description: a simple blog

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Jekyll-brotli settings
# -----------------------------------------------------------------------------
brotli:
  # The file extensions to compress.
  # The default is an empty array.
  # extensions:
  #  - .html
  #  - .css
  #  - .js
  #  - .json
  #  - .txt
  #  - .ico
  #  - .svg
  #  - .eot
  #  - .ttf
  #  - .woff
  #  - .woff2

# -----------------------------------------------------------------------------
# Jekyll remote theme settings
# -----------------------------------------------------------------------------
remote_theme: alshedivat/al-folio

# -----------------------------------------------------------------------------
# SEO
# -----------------------------------------------------------------------------

# Set to true to verify ownership of the website on Google Search Console
# and Bing Webmaster Tools.
# You need to add the verification file to the root of your repository.
# Looking at the theme, it seems like the following files are used:
# google_site_verification: google_verification_code.html
# bing_site_verification: BingSiteAuth.xml
# Other search engines are also supported. See the documentation for more details.
enable_google_verification: true
enable_bing_verification: false # Set to true to verify ownership of the website on Bing Webmaster Tools

# -----------------------------------------------------------------------------
# Giscus
# -----------------------------------------------------------------------------

# Giscus is a comments system powered by GitHub Discussions.
# To enable Giscus, you need to create a GitHub Discussion and then configure it here.
# For more information, see https://giscus.app/.
giscus:
  enabled: false # IMPORTANT: Ensure this is false if you don't use it.
  repo: # your GitHub repository for Giscus
  repo_id: # your GitHub repository ID for Giscus
  category: # your GitHub discussion category for Giscus
  category_id: # your GitHub discussion category ID for Giscus
  mapping: # your Giscus mapping
  strict: # your Giscus strict mode
  reactions_enabled: # your Giscus reactions enabled
  emit_metadata: # your Giscus emit metadata
  input_position: # your Giscus input position
  theme: # your Giscus theme
  lang: # your Giscus language

# -----------------------------------------------------------------------------
# Markdown settings
# -----------------------------------------------------------------------------

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # css_class: 'highlight'
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1

# -----------------------------------------------------------------------------
# Jekyll Feed settings
# -----------------------------------------------------------------------------

feed:
  # The path to the feed.
  # The default is /feed.xml.
  # path: /feed.xml

  # The number of posts to show in the feed.
  # The default is 10.
  # limit: 10

# -----------------------------------------------------------------------------
# Jekyll Paginate settings
# -----------------------------------------------------------------------------

paginate: 5 # The number of posts to show on the blog page.
paginate_path: /blog/page:num/ # The path to the pagination pages.

# -----------------------------------------------------------------------------
# Jekyll SEO Tag settings
# -----------------------------------------------------------------------------

# For more information, see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md.
# seo:
#   title: false
#   description: false
#   author: false
#   social:
#     name: John Doe
#     links:
#       - https://twitter.com/johndoe
#       - https://github.com/johndoe

# -----------------------------------------------------------------------------
# Jekyll Gist settings
# -----------------------------------------------------------------------------

# For more information, see https://github.com/jekyll/jekyll-gist.
# gist:
#   noscript: false

# -----------------------------------------------------------------------------
# Jekyll TOC settings
# -----------------------------------------------------------------------------

# For more information, see https://github.com/allejo/jekyll-toc.
toc:
  # The minimum number of headings to show the table of contents.
  # The default is 2.
  # min_headings: 2

  # The maximum number of headings to show the table of contents.
  # The default is 6.
  # max_headings: 6

  # The class of the table of contents.
  # The default is "toc".
  # css_class: toc

  # The list type of the table of contents.
  # The default is "ul".
  # list_type: ul

# -----------------------------------------------------------------------------
# Exclude from processing
# -----------------------------------------------------------------------------

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal exclusion list.
#
# Excluded items can be processed by explicitly listing the directories or
# files' path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------
    
# Add the url, version and integrity hash of the libraries you use in your site.
# The integrity hash is used to ensure that the library is not tampered with.
# Integrity hashes not provided by the libraries were generated using https://www.srihash.org/
third_party_libraries:
  download: false # if true, download the versions of the libraries specified below and use the downloaded files
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: "sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
    version: "1.22.4"
  chartjs:
    integrity:
      js: "sha256-0q+JdOlScWOHcunpUk21uab1jW7C1deBQARHtKMcaB4="
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@{{version}}/dist/chart.umd.min.js"
    version: "4.4.1"
  d3:
    integrity:
      js: "sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw="
    url:
      js: "https://cdn.jsdelivr.net/npm/d3@{{version}}/dist/d3.min.js"
    version: "7.8.5"
  diff2html:
    integrity:
      css: "sha256-IMBK4VNZp0ivwefSn51bswdsrhk0HoMTLc2GqFHFBXg="
      js: "sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF9bKz/DcbbY="
    url:
      css: "https://cdn.jsdelivr.net/npm/diff2html@{{version}}/bundles/css/diff2html.min.css"
      js: "https://cdn.jsdelivr.net/npm/diff2html@{{version}}/bundles/js/diff2html-ui.min.js"
    version: "3.4.47"
  echarts:
    integrity:
      js:
        library: "sha256-QvgynZibb2U53SsVu98NggJXYqwRL7tg3FeyfXvPOUY="
        dark_theme: "sha256-sm6Ui9w41++ZCWmIWDLC18a6ki72FQpWDiYTDxEPXwU="
    url:
      js:
        library: "https://cdn.jsdelivr.net/npm/echarts@{{version}}/dist/echarts.min.js"
        dark_theme: "https://cdn.jsdelivr.net/npm/echarts@{{version}}/theme/dark-fresh-cut.js"
    version: "5.5.0"
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  highlightjs:
    integrity:
      css:
        light: "sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fZ/6ksAqDCM8GY="
        dark: "sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk="
    url:
      css:
        light: "https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github.min.css"
        dark: "https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github-dark.min.css"
    version: "11.9.0"
  imagesloaded:
    integrity:
      js: "sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc="
    url:
      js: https://cdn.jsdelivr.net/npm/imagesloaded@{{version}}/imagesloaded.pkgd.min.js
    version: "5.0.0"
  img-comparison-slider:
    integrity:
      css: "sha256-3qTIuuUWIFnnU3LpQMjqiXc0p09rvd0dmj+WkpQXSR8="
      js: "sha256-EXHg3x1K4oIWdyohPeKX2ZS++Wxt/FRPH7Nl01nat1o="
      map: "sha256-3wfqS2WU5kGA/ePcgFzJXl5oSN1QsgZI4/edprTgX8w="
    url:
      css: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/styles.min.css"
      js: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.min.js"
      map: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.js.map"
    version: "8.0.6"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js"
    version: "3.6.0"
  leaflet:
    integrity:
      css: "sha256-q9ba7o845pMPFU+zcAll8rv+gC+fSovKsOoNQ6cynuQ="
      js: "sha256-MgH13bFTTNqsnuEoqNPBLDaqxjGH+lCpqrukmXc8Ppg="
      js_map: "sha256-YAoQ3FzREN4GmVENMir8vgHHypC0xfSK3CAxTHCqx1M="
    local:
      images: "images/"
    url:
      css: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.min.css"
      images: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/images/"
      js: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.js.map"
    version: "1.9.4"
  lightbox2:
    integrity:
      css: "sha256-uypRbsAiJcFInM/ndyI/JHpzNe6DtUNXaWEUWEPfMGo="
      js: "sha256-A6jI5V9s1JznkWwsBaRK8kSeXLgIqQfxfnvdDOZEURY="
    url:
      css: "https://cdn.jsdelivr.net/npm/lightbox2@{{version}}/dist/css/lightbox.min.css"
      js: "https://cdn.jsdelivr.net/npm/lightbox2@{{version}}/dist/js/lightbox.min.js"
    version: "2.11.5"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    local:
      fonts: "output/chtml/fonts/woff-v2/"
    url:
      fonts: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/output/chtml/fonts/woff-v2/"
      js: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/tex-mml-chtml.js"
    version: "3.2.2"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@{{version}}/dist/masonry.pkgd.min.js"
    version: "4.2.2"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      css_map: "sha256-iYYMNfsJdVZjvsebJulg09miBXM4/GMTJgv1u5EZFFM="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
      js_map: "sha256-UPgyn4YNsT0khkBK5553QwhnlbTlU0aa+igyc6qP1bE="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css"
      css_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css.map"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js.map"
    version: "4.20.0"
  medium_zoom:
    integrity:
      js: "sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@{{version}}/dist/medium-zoom.min.js"
    version: "1.1.0"
  mermaid:
    integrity:
      js: "sha256-TtLOdUA8mstPoO6sGvHIGx2ceXrrX4KgIItO06XOn8A="
    url:
      js: "https://cdn.jsdelivr.net/npm/mermaid@{{version}}/dist/mermaid.min.js"
    version: "10.7.0"
  photoswipe:
    integrity:
      js: "sha256-VCBpdxvrNNxGHNuTdNqK9kPFkev2XY7DYzHdmgaB69Q="
    url:
      css: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe.min.css"
      js: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe.esm.min.js"
    version: "5.4.4"
  photoswipe-lightbox:
    integrity:
      js: "sha256-uCw4VgT5DMdwgtjhvU9e98nT2mLZXcw/8WkaTrDd3RI="
    url:
      js: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe-lightbox.esm.min.js"
    version: "5.4.4"
  plotly:
    integrity:
      js: "sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q="
    url:
      js: "https://cdn.jsdelivr.net/npm/plotly.js@{{version}}/dist/plotly.min.js"
    version: "3.0.1"
  polyfill:
    url:
      js: "https://cdnjs.cloudflare.com/polyfill/v{{version}}/polyfill.min.js?features=es6"
    version: "3"
  pseudocode:
    integrity:
      css: "sha256-VwMV//xgBPDyRFVSOshhRhzJRDyBmIACniLPpeXNUdc="
      js: "sha256-aVkDxqyzrB+ExUsOY9PdyelkDhn/DfrjWu08aVpqNlo="
    url:
      css: "https://cdn.jsdelivr.net/npm/pseudocode@{{version}}/build/pseudocode.min.css"
      js: "https://cdn.jsdelivr.net/npm/pseudocode@{{version}}/build/pseudocode.min.js"
    version: "2.4.1"
  spotlight:
    integrity:
      css: "sha256-Dsvkx8BU8ntk9Iv+4sCkgHRynYSQQFP6gJfBN5STFLY="
    url:
      css: "https://cdn.jsdelivr.net/npm/spotlight.js@{{version}}/dist/css/spotlight.min.css"
      js: "https://cdn.jsdelivr.net/npm/spotlight.js@{{version}}/dist/spotlight.bundle.min.js"
    version: "0.7.8"
  swiper:
    integrity:
      css: "sha256-yUoNxsvX+Vo8Trj3lZ/Y5ZBf8HlBFsB6Xwm7rH75/9E="
      js: "sha256-BPrwikijIybg9OQC5SYFFqhBjERYOn97tCureFgYH1E="
      map: "sha256-lbF5CsospW93otqvWOIbbhj80CjazrZXvamD7nC7TBI="
    url:
      css: "https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-bundle.min.css"
      js: "https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-element-bundle.min.js"
      map: "https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-element-bundle.min.js.map"
    version: "11.0.5"
  swiper-map:
    integrity:
      js: "sha256-hlZaH8ySXX97bZaetnrtYlKuhx3oEXFz/s2IXchu6vk="
    url:
      js: "https://cdn.jsdelivr.net/npm/swiper@11.1.0/swiper-element-bundle.min.js.map"
    version: "11.0.5"
  vega:
    integrity:
      js: "sha256-Yot/cfgMMMpFwkp/5azR20Tfkt24PFqQ6IQS+80HIZs="
      js_map: "sha256-z0x9ICA65dPkZ0JVa9wTImfF6n7AJsKc6WlFE96/wNA="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega@{{version}}/build/vega.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/vega@{{version}}/build/vega.min.js.map"
    version: "5.27.0"
  vega-embed:
    integrity:
      js: "sha256-FPCJ9JYCC9AZSpvC/t/wHBX7ybueZhIqOMjpWqfl3DU="
      js_map: "sha256-VBbfSEFYSMdX/rTdGrONEHNP6BprCB7H/LpMMNt/cPA="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega-embed@{{version}}/build/vega-embed.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/vega-embed@{{version}}/build/vega-embed.min.js.map"
    version: "6.24.0"
  vega-lite:
    integrity:
      js: "sha256-TvBvIS5jUN4BSy009usRjNzjI1qRrHPYv7xVLJyjUyw="
      js_map: "sha256-l2I4D5JC23Ulsu6e3sKVe5AJ+r+DFkzkKnZS8nUGz28="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega-lite@{{version}}/build/vega-lite.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/vega-lite@{{version}}/build/vega-lite.min.js.map"
    version: "5.16.3"
  venobox:
    integrity:
      css: "sha256-ohJEB0/WsBOdBD+gQO/MGfyJSbTUI8OOLbQGdkxD6Cg="
      js: "sha256-LsGXHsHMMmTcz3KqTaWvLv6ome+7pRiic2LPnzTfiSo="
    url:
      css: "https://cdn.jsdelivr.net/npm/venobox@{{version}}/dist/venobox.min.css"
      js: "https://cdn.jsdelivr.net/npm/venobox@{{version}}/dist/venobox.min.js"
    version: "2.1.8"
